package com.example.ttdaa;

public class Database_kho {
    Integer[] image ={
            R.drawable.basket,
            R.drawable.motor,
            R.drawable.sugar,
            R.drawable.table,
            R.drawable.taxi,
            R.drawable.thread,
            R.drawable.tiger,
            R.drawable.toad,
            R.drawable.tomato,
            R.drawable.tree,
            R.drawable.trip,
            R.drawable.tube,
            R.drawable.turkey,
            R.drawable.cycle,

            R.drawable.body,
            R.drawable.city,
            R.drawable.hand,
            R.drawable.party,
            R.drawable.phone,
            R.drawable.potato,
            R.drawable.pyjama,
            R.drawable.shirt,
            R.drawable.team,
            R.drawable.time,
            R.drawable.water,
            R.drawable.women,
            R.drawable.banana,
            R.drawable.screen,
            R.drawable.house,
            R.drawable.noodle
    };

    String[] question ={
            "basket",
            "motor",
            "sugar",
            "table",
            "taxi",
            "thread",
            "tiger",
            "toad",
            "tomato",
            "tree",
            "trip",
            "tube",
            "turkey",
            "cycle",

            "body",
            "city",
            "hand",
            "party",
            "phone",
            "potato",
            "pyjama",
            "shirt",
            "team",
            "time",
            "water",
            "women",
            "banana",
            "screen",
            "house",
            "noodle",


    };

    String[] answers ={
            "basket",
            "motor",
            "sugar",
            "table",
            "taxi",
            "thread",
            "tiger",
            "toad",
            "tomato",
            "tree",
            "trip",
            "tube",
            "turkey",
            "cycle",

            "body",
            "city",
            "hand",
            "party",
            "phone",
            "potato",
            "pyjama",
            "shirt",
            "team",
            "time",
            "water",
            "women",
            "banana",
            "screen",
            "house",
            "noodle",
    };
}

